# Generated by Django 4.2.1 on 2023-06-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_ID', models.IntegerField()),
                ('order_ID', models.CharField(max_length=100)),
                ('order_Date', models.CharField(max_length=100)),
                ('sent_Date', models.CharField(max_length=100)),
                ('post_Way', models.IntegerField()),
                ('customer_ID', models.CharField(max_length=100)),
                ('customer_Name', models.CharField(max_length=100)),
                ('split', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('product_ID', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('son_Series', models.CharField(max_length=100)),
                ('product_Name', models.CharField(max_length=100)),
                ('sales_Total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('product_Num', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
